[package]
name = "usbd-midi"
version = "0.2.0"
authors = ["beau trepp <beautrepp@gmail.com>", "Florian Jung <flo@windfis.ch>"]
edition = "2018"
description = "A usb-midi implementation for usb-device"
homepage = "https://github.com/btrepp/usbd-midi"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.2"
usb-device = "0.2.3"
midi-convert = "0.1.1"
midi-types = "0.1.4"
